# Generated by Django 3.2.12 on 2022-03-07 15:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAS', 'Passport'), ('NID', 'National ID')], default='PAS', max_length=3, verbose_name='Document Type')),
                ('document_identification_number', models.CharField(max_length=50, verbose_name='Document Identification Number')),
                ('document_expiry_date', models.DateField(verbose_name='Document Expiry Date')),
                ('document_issuing_country', models.CharField(max_length=50, verbose_name='Document Issuing Country')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Unspecified')], default='PAS', max_length=2, verbose_name='Sex')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('requester_first_name', models.CharField(max_length=100, verbose_name='Requester First Name')),
                ('requester_last_name', models.CharField(max_length=100, verbose_name='Requester Last Name')),
                ('requester_phone_number', models.CharField(help_text='Please include country prefix e.g. +40723000123', max_length=30, verbose_name='Requester Phone Number')),
                ('institution_type', models.CharField(choices=[('MED', 'Medical Institution'), ('NGO', 'Non-Governmental Organization'), ('PER', 'Person'), ('COM', 'Company')], default='MED', max_length=3, verbose_name='Institution Type')),
                ('institution_name', models.CharField(blank=True, help_text='Fill in only if requester is not a Person', max_length=250, null=True, verbose_name='Institution Name')),
                ('complete_diagnostic', models.TextField(help_text='Put some helful explanation here...', verbose_name='Complete Diagnostic')),
                ('available_diagnostic', models.TextField(blank=True, help_text='Put some helful explanation here...', null=True, verbose_name='Available Diagnostic / Request Reason')),
                ('tumor_type', models.CharField(choices=[('S', 'Solid'), ('H', 'Hemato')], default='S', max_length=2, verbose_name='Tumor Type')),
                ('therapy_needs', multiselectfield.db.fields.MultiSelectField(choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant'), ('OTH', 'Other')], max_length=35, verbose_name='Therapy Needs')),
                ('other_therapy_needs', models.CharField(blank=True, max_length=250, null=True, verbose_name='Other Therapy Needs')),
                ('clinical_status_comments', models.TextField(blank=True, null=True, verbose_name='Clinical Status Comments')),
                ('child_current_address', models.CharField(max_length=100, verbose_name='Child Current Address')),
                ('child_current_city', models.CharField(max_length=100, verbose_name='Child Current City')),
                ('child_current_county', models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current County')),
                ('child_current_country', models.CharField(max_length=100, verbose_name='Child Current Country')),
                ('estimated_arrival_dt', models.DateTimeField(verbose_name='Estimated Arrival')),
                ('redirect_info', models.TextField(help_text='Redirection to a different specialty. Provide all info, including contact!', verbose_name='Redirect Info')),
                ('is_direct_request', models.BooleanField(default=False, help_text='Patient has directly presented him/herself in the clinc without contact?', verbose_name='Direct Request')),
            ],
            options={
                'verbose_name': 'Patient Request',
                'verbose_name_plural': 'Patient Requests',
            },
        ),
    ]
