# Generated by Django 3.2.12 on 2022-03-06 23:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAS', 'Passport'), ('NID', 'National ID')], default='PAS', max_length=3, verbose_name='Document Type')),
                ('document_expiry_date', models.DateField(verbose_name='Document Expiry Date')),
                ('document_issuing_country', models.CharField(max_length=50, verbose_name='Document Issuing Country')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Unspecified')], default='PAS', max_length=2, verbose_name='Sex')),
                ('requester_first_name', models.CharField(max_length=100, verbose_name='Requester First Name')),
                ('requester_last_name', models.CharField(max_length=100, verbose_name='Requester Last Name')),
                ('requester_phone_number', models.CharField(help_text='Please include country prefix e.g. +40723000123', max_length=30, verbose_name='Requester Phone Number')),
                ('requester_is_medical_institution', models.BooleanField(default=False, verbose_name='Medical Institution')),
                ('medical_institution_name', models.CharField(blank=True, help_text='Fill in only if requester is a medical institution', max_length=250, null=True, verbose_name='Medical Institution Name')),
                ('complete_diagnostic', models.TextField(help_text='Put some helful explanation here...', verbose_name='Complete Diagnostic')),
                ('available_diagnostic', models.TextField(help_text='Put some helful explanation here...', verbose_name='Available Diagnostic / Request Reason')),
                ('tumor_type', models.CharField(choices=[('S', 'Solid'), ('H', 'Hemato')], default='S', max_length=2, verbose_name='Tumor Type')),
                ('therapy_needs', multiselectfield.db.fields.MultiSelectField(choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant')], max_length=31, verbose_name='Therapy Needs')),
                ('location', models.CharField(help_text='Where is the child at the moment of the request', max_length=250, verbose_name='Child Location')),
                ('clinical_status', models.CharField(max_length=250, verbose_name='Child Location')),
                ('estimated_arrival_dt', models.DateTimeField(verbose_name='Estimated Arrival')),
                ('redirect_info', models.TextField(help_text='Redirection to a different specialty. Provide all info, including contact!', verbose_name='Redirect Info')),
                ('is_direct_request', models.BooleanField(default=False, help_text='Patient has directly presented him/herself in the clinc without contact?', verbose_name='Direct Request')),
            ],
        ),
    ]
