# Generated by Django 3.2.12 on 2022-03-07 15:59

import dispatch.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=dispatch.models.patient_request_upload)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.patientrequest')),
            ],
        ),
    ]
