# Generated by Django 3.2.12 on 2022-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='clinical_status',
            field=models.CharField(max_length=250, verbose_name='Clinical Status'),
        ),
    ]
