# Generated by Django 3.2.12 on 2022-03-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='estimated_arrival_dt',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='is_direct_request',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='redirect_info',
        ),
    ]
