# Generated by Django 3.2.12 on 2022-03-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_patientrequestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='source_medical_institution_contact_person',
            field=models.CharField(default='asdasda', max_length=150, verbose_name='Contact Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='source_medical_institution_name',
            field=models.CharField(default='asdasda', max_length=150, verbose_name='Institution Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='source_medical_institution_phone_number',
            field=models.CharField(default=1234567, help_text="Contact Person's phone number. Please include country prefix e.g. +40723000123", max_length=30, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='redirect_info',
            field=models.TextField(blank=True, help_text='Redirection to a different specialty. Provide all info, including contact!', null=True, verbose_name='Redirect Info'),
        ),
        migrations.CreateModel(
            name='MedicalAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_dr_full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Receiving Dr Full Name')),
                ('receiving_dr_phone_number', models.CharField(blank=True, help_text='Please include country prefix e.g. +40723000123', max_length=30, null=True, verbose_name='Receiving Dr Phone Number')),
                ('hospitalization_start', models.DateField(blank=True, help_text='Only with confirmation from the receiving clinic!', null=True, verbose_name='Hospitalization Start')),
                ('hospitalization_end', models.DateField(blank=True, null=True, verbose_name='Hospitalization End')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dispatch.patientrequest')),
            ],
        ),
    ]
