# Generated by Django 3.2.12 on 2022-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_auto_20220311_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Fill in only if requester is not a Person', max_length=250, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='institution_type',
            field=models.CharField(choices=[('MED', 'Medical Institution'), ('NGO', 'Non-Governmental Organization'), ('PER', 'Person'), ('COM', 'Company')], default='MED', max_length=3, verbose_name='Requester Type'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='requester_email',
            field=models.EmailField(max_length=254, verbose_name='Requester Email'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='requester_first_name',
            field=models.CharField(max_length=100, verbose_name='Requester First Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='requester_last_name',
            field=models.CharField(max_length=100, verbose_name='Requester Last Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='requester_phone_number',
            field=models.CharField(help_text='Please include country prefix e.g. +40723000123', max_length=30, verbose_name='Requester Phone Number'),
        ),
    ]
