# Generated by Django 3.2.12 on 2022-03-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_alter_patientrequest_clinical_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrequest',
            options={'verbose_name': 'Patient Request', 'verbose_name_plural': 'Patient Requests'},
        ),
    ]
