# Generated by Django 3.2.12 on 2022-03-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_auto_20220311_1625'),
        ('dispatch', '0003_auto_20220311_1637'),
    ]

    operations = [
    ]
