# Generated by Django 3.2.12 on 2022-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_patientrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='document_identification_number',
            field=models.CharField(default=12345, max_length=50, verbose_name='Document Identification Number'),
            preserve_default=False,
        ),
    ]
