# Generated by Django 3.2.12 on 2022-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_auto_20220308_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='source_medical_institution_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
