# Generated by Django 3.2.12 on 2022-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_merge_0003_auto_20220311_1625_0003_auto_20220311_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalassistance',
            name='needs_transfer',
        ),
        migrations.AlterField(
            model_name='medicalassistance',
            name='case_status',
            field=models.CharField(choices=[('P', 'Case Pending'), ('R', 'Clinic is Ready for takeover'), ('T', 'Taken over by Clinic'), ('TP', 'Taken over previously, in person'), ('RE', 'Redirected')], default='P', max_length=3, verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
