# Generated by Django 3.2.12 on 2022-03-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_patientrequest_source_medical_institution_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrequest',
            old_name='source_medical_institution_contact_person',
            new_name='origin_medical_institution_contact_person',
        ),
        migrations.RenameField(
            model_name='patientrequest',
            old_name='source_medical_institution_email',
            new_name='origin_medical_institution_email',
        ),
        migrations.RenameField(
            model_name='patientrequest',
            old_name='source_medical_institution_name',
            new_name='origin_medical_institution_name',
        ),
        migrations.RenameField(
            model_name='patientrequest',
            old_name='source_medical_institution_phone_number',
            new_name='origin_medical_institution_phone_number',
        ),
    ]
