# Generated by Django 3.2.12 on 2022-03-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_logisticandsocialassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='accommodation_required',
            field=models.BooleanField(default=False, help_text='Wether accommodation is required for this assistence', verbose_name='Accommodation Required'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='transport_required',
            field=models.BooleanField(default=False, help_text='Wether national or international transportation is required for this assistence', verbose_name='Transport Required'),
        ),
    ]
