# Generated by Django 3.2.12 on 2022-03-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_auto_20220308_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Companion Name')),
                ('companion_relationship', models.CharField(blank=True, max_length=150, null=True, verbose_name='Companion Relationship')),
                ('companion_phone_number', models.CharField(blank=True, help_text='Please include country prefix e.g. +40723000123', max_length=30, null=True, verbose_name='Companion Phone Number')),
                ('companion_other_details', models.TextField(blank=True, null=True, verbose_name='Companion Other Details')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.patientrequest')),
            ],
        ),
    ]
