# Generated by Django 3.2.12 on 2022-03-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_companion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tumor_type', models.CharField(choices=[('S', 'Solid'), ('H', 'Hematologic')], default='S', max_length=2, verbose_name='Tumor Type')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('county', models.CharField(choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CL', 'Călărași'), ('CS', 'Caraș-Severin'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea')], max_length=3, verbose_name='County')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('hospitalization_office_email', models.EmailField(max_length=254, verbose_name='Hospitalization Office Email')),
                ('hospitalization_office_phone_number', models.CharField(max_length=30, verbose_name='Hospitalization Office Phone Number')),
                ('head_of_dept_name', models.CharField(max_length=100, verbose_name='Head Of Department Name')),
                ('head_of_dept_email', models.EmailField(max_length=254, verbose_name='Head Of Department Email')),
                ('dept_phone', models.CharField(max_length=30, verbose_name='Department Phone Number')),
                ('available_beds', models.SmallIntegerField(default=0, verbose_name='Available Beds')),
            ],
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='tumor_type',
            field=models.CharField(choices=[('S', 'Solid'), ('H', 'Hematologic')], default='S', max_length=2, verbose_name='Tumor Type'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.clinic'),
        ),
    ]
