# Generated by Django 3.2.12 on 2022-03-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_alter_patientrequest_known_complete_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='known_complete_diagnostic',
            field=models.CharField(choices=[(0, 'No'), (1, 'Yes')], default=0, max_length=2, verbose_name='Complete Diagnostic Known'),
        ),
    ]
