# Generated by Django 3.2.12 on 2022-03-11 17:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_alter_patientrequest_known_complete_diagnostic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='institution_type',
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='birth_place',
            field=models.CharField(default='somewhere', help_text='Birth Place: City, Country', max_length=250, verbose_name='Birth Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='requester_category',
            field=models.CharField(choices=[('MED', 'Medical Institution'), ('NGO', 'Non-Governmental Organization'), ('PER', 'Person'), ('COM', 'Company')], default='MED', max_length=3, verbose_name='Requester Category'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='therapy_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring after Treatment'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant Waitlist'), ('OTH', 'Other')], max_length=35, verbose_name='Therapy Services'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Pacient First Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='PacientLast Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='therapy_needs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring after Treatment'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant Waitlist'), ('OTH', 'Other')], max_length=35, verbose_name='Therapy Needs'),
        ),
    ]
