# Generated by Django 3.2.12 on 2022-03-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_alter_medicalassistance_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalassistance',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_clinics', to='dispatch.clinic'),
        ),
    ]
