# Generated by Django 3.2.12 on 2022-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_alter_medicalassistance_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalassistance',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='med_assistance', to='dispatch.patientrequest'),
        ),
    ]
