# Generated by Django 3.2.12 on 2022-03-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_auto_20220311_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='accommodation_rep_external',
            field=models.BooleanField(default=False, help_text='Check if the responsible is outside Dăruiește Aripi organization', verbose_name='Accomodation responsibility'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='accommodation_rep_external_details',
            field=models.TextField(blank=True, verbose_name='External Representative Details'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='assistance_rep_external',
            field=models.BooleanField(default=False, help_text='Check if the responsible is outside Dăruiește Aripi organization', verbose_name='Assistance Representative'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='assistance_required',
            field=models.BooleanField(default=False, help_text='Wether local assistance is required', verbose_name='Local Assistance Required'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='destination_location',
            field=models.CharField(blank=True, help_text='Departing from: City, Country', max_length=200, verbose_name='Destination Location'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='transport_rep_external',
            field=models.BooleanField(default=False, help_text='Check if the responsible is outside Dăruiește Aripi organization', verbose_name='Transport Responsability'),
        ),
    ]
