# Generated by Django 3.2.12 on 2022-03-11 17:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_auto_20220311_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='therapy_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring after Treatment'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant Waitlist'), ('OTH', 'Other')], max_length=35, verbose_name='Medical Services'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='accommodation_rep_external_details',
            field=models.TextField(blank=True, verbose_name='External Accomodation Representative Details'),
        ),
    ]
