# Generated by Django 3.2.12 on 2022-03-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_alter_medicalassistance_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logsol_assistance', to='dispatch.patientrequest'),
        ),
    ]
