# Generated by Django 3.2.12 on 2022-03-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_alter_logisticandsocialassistance_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='dispatch.patientrequest'),
        ),
    ]
