# Generated by Django 3.2.12 on 2022-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_auto_20220311_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='translator_contact',
            field=models.TextField(blank=True, verbose_name='Translator Contact'),
        ),
    ]
