# Generated by Django 3.2.12 on 2022-03-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_alter_companion_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Clinic', 'verbose_name_plural': 'Clinics'},
        ),
    ]
