# Generated by Django 3.2.12 on 2022-03-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0015_alter_clinic_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientrequest',
            unique_together={('first_name', 'last_name', 'birth_date', 'age')},
        ),
    ]
