# Generated by Django 3.2.12 on 2022-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0015_alter_patientrequest_known_complete_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Pacient Last Name'),
        ),
    ]
