# Generated by Django 3.2.12 on 2022-03-16 16:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0016_alter_patientrequest_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='comorbidities_icd10',
            field=models.TextField(blank=True, verbose_name='Comorbidities (ICD-10)'),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='main_diagnostic_icd10',
            field=models.TextField(blank=True, verbose_name='Main Diagnosis (ICD-10)'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='therapy_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring after Treatment'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant Waitlist'), ('ICM', 'Intensive Care Medicine'), ('OTH', 'Other')], max_length=39, verbose_name='Medical Services'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='known_complete_diagnostic',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=2, verbose_name='Complete Diagnostic Known'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='requester_category',
            field=models.CharField(choices=[('MED', 'Medical Institution'), ('COSU', 'Ministry of Health / COSU'), ('NGO', 'Non-Governmental Organization'), ('PER', 'Person'), ('COM', 'Company')], default='MED', max_length=4, verbose_name='Requester Category'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='therapy_needs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring after Treatment'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant Waitlist'), ('ICM', 'Intensive Care Medicine'), ('OTH', 'Other')], max_length=39, verbose_name='Therapy Needs'),
        ),
    ]
