# Generated by Django 3.2.12 on 2022-03-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0016_alter_patientrequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='document_expiry_date',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='document_identification_number',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='document_issuing_country',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='document_type',
        ),
    ]
