# Generated by Django 3.2.12 on 2022-03-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0018_auto_20220309_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='available_diagnostic',
        ),
        migrations.RemoveField(
            model_name='patientrequest',
            name='clinical_status_comments',
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='current_clinical_status',
            field=models.TextField(blank=True, null=True, verbose_name='Current Clinical Status'),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='date_diagnosed',
            field=models.DateField(blank=True, null=True, verbose_name='Date Diagnosed'),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='diagnosing_institution_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnosing Institution Name'),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='diagnostic_class',
            field=models.CharField(choices=[('LAMM', 'Leucemii, afecțiuni mieloproliferative și mielodisplazice'), ('LNR', 'Limfoame și neoplasme reticuloendoteliale'), ('SNCNII', 'SNC și neoplasme intracraniene și intraspinale'), ('NATCNP', 'Neuroblastom și alte tumori ale celulelor nervoase periferice'), ('R', 'Retinoblastom'), ('TR', 'Tumori renale'), ('TH', 'Tumori hepatice'), ('TMO', 'Tumori maligne ale oaselor'), ('SPMATE', 'Sarcoame de părți moi și alte țesuturi extraosoase'), ('TTNG', 'Tumori terofoblastice și neoplasme ale gonadelor'), ('ANMEMM', 'Alte neoplasme maligne epiteliale și melanoame maligne'), ('ANMN', 'Alte neoplasme maligne nespecificate')], default='R', max_length=10, verbose_name='Diagnostic Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='general_problem_description',
            field=models.TextField(blank=True, help_text="Describe the Child's medical issue", null=True, verbose_name='General Problem Description'),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='known_complete_diagnostic',
            field=models.BooleanField(default=False, verbose_name='Complete Diagnostic Known'),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='medical_documents_checked',
            field=models.BooleanField(default=False, verbose_name='Medical Documents Checked'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='complete_diagnostic',
            field=models.TextField(blank=True, null=True, verbose_name='Complete Diagnostic'),
        ),
    ]
