# Generated by Django 3.2.12 on 2022-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0019_auto_20220309_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='child_current_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current Address'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='child_current_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current City'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='child_current_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current Country'),
        ),
    ]
