# Generated by Django 3.2.12 on 2022-03-09 21:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0020_auto_20220309_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalassistance',
            name='hospitalization_end',
        ),
        migrations.RemoveField(
            model_name='medicalassistance',
            name='receiving_dr_phone_number',
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='case_status',
            field=models.CharField(choices=[('P', 'Case Pending'), ('R', 'Clinic is Ready for takeover'), ('T', 'Taken over by Clinic'), ('TP', 'Taken over previously, in person')], default='P', max_length=3, verbose_name='Case Status'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='estimated_arrival_time',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated Arrival Time'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='international_redirect',
            field=models.BooleanField(default=False, verbose_name='International Redirect'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='needs_transfer',
            field=models.BooleanField(default=False, verbose_name='Needs Transfer'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='specialty',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='town',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='tumor_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Solid'), ('H', 'Hematologic')], max_length=2, verbose_name='Tumor Type'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='origin_medical_institution_contact_person',
            field=models.CharField(blank=True, help_text='Full Name of the contact person', max_length=150, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='origin_medical_institution_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='origin_medical_institution_phone_number',
            field=models.CharField(blank=True, help_text="Contact Person's phone number. Please include country prefix e.g. +40723000123", max_length=30, null=True, verbose_name='Phone Number'),
        ),
    ]
