# Generated by Django 3.2.12 on 2022-03-09 21:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0021_auto_20220309_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='tumor_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Solid'), ('H', 'Hematologic')], max_length=3, verbose_name='Tumor Type'),
        ),
    ]
