# Generated by Django 3.2.12 on 2022-03-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0022_alter_clinic_tumor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalassistance',
            name='redirect_institution',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Redirect Institution'),
        ),
    ]
