# Generated by Django 3.2.12 on 2022-03-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0023_medicalassistance_redirect_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalassistance',
            name='estimated_arrival_time',
        ),
        migrations.AddField(
            model_name='medicalassistance',
            name='estimated_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated Arrival Date'),
        ),
    ]
