# Generated by Django 3.2.12 on 2022-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0027_alter_medicalassistance_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalassistance',
            name='case_status',
            field=models.CharField(choices=[('P', 'Case Pending'), ('R', 'Clinic is Ready for takeover'), ('T', 'Taken over by Clinic'), ('TP', 'Taken over previously, in person')], default='P', max_length=3, verbose_name='Case Status'),
        ),
    ]
