# Generated by Django 3.2.12 on 2022-03-10 10:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0029_alter_clinic_tumor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='tumor_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Solid'), ('H', 'Hematologic')], max_length=3, verbose_name='Tumor Type'),
        ),
    ]
