# Generated by Django 3.2.12 on 2022-03-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0030_alter_clinic_tumor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticandsocialassistance',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='logisticandsocialassistance',
            name='destination_asisting_entity_details',
        ),
        migrations.AddField(
            model_name='logisticandsocialassistance',
            name='accommodation_rep_external',
            field=models.BooleanField(default=False, help_text='Is the accommodation representative external to the organization?', verbose_name='External accommodation Representative'),
        ),
        migrations.AddField(
            model_name='logisticandsocialassistance',
            name='accommodation_rep_external_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticandsocialassistance',
            name='destination_location',
            field=models.CharField(blank=True, help_text='Departing from: City, Country', max_length=200, null=True, verbose_name='Pick Up Location'),
        ),
        migrations.AddField(
            model_name='logisticandsocialassistance',
            name='transport_rep_external',
            field=models.BooleanField(default=False, help_text='Is the transport representative external to the organization?', verbose_name='External Transport Representative'),
        ),
        migrations.AddField(
            model_name='logisticandsocialassistance',
            name='transport_rep_external_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='accommodation_details',
            field=models.TextField(blank=True, null=True, verbose_name='Accommodation Details'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='pick_up_location',
            field=models.CharField(blank=True, help_text='Departing from: City, Country', max_length=200, null=True, verbose_name='Pick Up Location'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='transport_details',
            field=models.TextField(blank=True, null=True, verbose_name='Transport Details'),
        ),
    ]
