# Generated by Django 3.2.12 on 2022-03-11 08:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0033_auto_20220310_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='therapy_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant'), ('OTH', 'Other')], default=['CHE', 'SUR'], max_length=35, verbose_name='Therapy Services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Clinic Name'),
        ),
    ]
