# Generated by Django 3.2.12 on 2022-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0035_auto_20220311_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='accommodation_status',
            field=models.CharField(choices=[('US', 'Unsolved'), ('S', 'Solved')], default='US', max_length=2, verbose_name='Accommodation Status'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='assistance_status',
            field=models.CharField(choices=[('US', 'Unsolved'), ('S', 'Solved')], default='US', max_length=2, verbose_name='Assistance Status'),
        ),
        migrations.AlterField(
            model_name='logisticandsocialassistance',
            name='transport_status',
            field=models.CharField(choices=[('US', 'Unsolved'), ('S', 'Solved')], default='US', max_length=2, verbose_name='Transport Status'),
        ),
    ]
