# Generated by Django 3.2.12 on 2022-03-11 10:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0036_auto_20220311_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='child_current_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current Address'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='child_current_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current City'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='child_current_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current Country'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='child_current_county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Child Current County'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='complete_diagnostic',
            field=models.TextField(blank=True, null=True, verbose_name='Complete Diagnostic'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='current_clinical_status',
            field=models.TextField(blank=True, null=True, verbose_name='Current Clinical Status'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='diagnosing_institution_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnosing Institution Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='diagnostic_class',
            field=models.CharField(blank=True, choices=[('LAMM', 'Leucemii, afecțiuni mieloproliferative și mielodisplazice'), ('LNR', 'Limfoame și neoplasme reticuloendoteliale'), ('SNCNII', 'SNC și neoplasme intracraniene și intraspinale'), ('NATCNP', 'Neuroblastom și alte tumori ale celulelor nervoase periferice'), ('R', 'Retinoblastom'), ('TR', 'Tumori renale'), ('TH', 'Tumori hepatice'), ('TMO', 'Tumori maligne ale oaselor'), ('SPMATE', 'Sarcoame de părți moi și alte țesuturi extraosoase'), ('TTNG', 'Tumori terofoblastice și neoplasme ale gonadelor'), ('ANMEMM', 'Alte neoplasme maligne epiteliale și melanoame maligne'), ('ANMN', 'Alte neoplasme maligne nespecificate')], max_length=10, null=True, verbose_name='Diagnostic Class'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='estimated_arrival_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Arrival'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='general_problem_description',
            field=models.TextField(blank=True, help_text="Describe the Child's medical issue", null=True, verbose_name='General Problem Description'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Fill in only if requester is not a Person', max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='origin_medical_institution_contact_person',
            field=models.CharField(blank=True, help_text='Full Name of the contact person', max_length=150, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='origin_medical_institution_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='origin_medical_institution_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='origin_medical_institution_phone_number',
            field=models.CharField(blank=True, help_text="Contact Person's phone number. Please include country prefix e.g. +40723000123", max_length=30, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='other_therapy_needs',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Other Therapy Needs'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='therapy_needs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHE', 'Chemotherapy'), ('SUR', 'Surgical'), ('PAL', 'Palliative'), ('MON', 'Monitoring'), ('INV', 'Diagnostic Investigation'), ('SUT', 'Supportive Treatment'), ('RAD', 'Radiotherapy'), ('TRA', 'Transplant'), ('OTH', 'Other')], max_length=35, null=True, verbose_name='Therapy Needs'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='tumor_type',
            field=models.CharField(blank=True, choices=[('S', 'Solid'), ('H', 'Hematologic')], max_length=2, null=True, verbose_name='Tumor Type'),
        ),
    ]
