# Generated by Django 3.2.12 on 2022-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoped_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('patient_request', 'Patient Request Form Email')], max_length=50, unique=True, verbose_name='Template'),
        ),
    ]
