# Generated by Django 3.2.12 on 2022-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoped_site', '0002_alter_emailtemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='lang',
            field=models.CharField(choices=[('ro', 'Romanian'), ('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('patient_request', 'Patient Request Form')], max_length=50, verbose_name='Template'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('template', 'lang')},
        ),
    ]
